language: rust
rust:
  - 1.12.0
  - stable
  - nightly
os:
  - linux
  - osx

# Using 16MB stacks for deep test/debug recursion
env:
  global:
    - RUST_MIN_STACK=16777216

script:
  - cargo build
  - cargo test
